<a href="https://colab.research.google.com/github/JIJASH/ml_from_scratch/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction to NumPy

What will we cover?
- Creating arrays
- Multidimensional arrays
- Randomly generated arrays
- Element wise operations
  - Comparison operations
  - Logical operations
- Summarizing operations

### ✅Single Dimensional arrays

In [2]:
import numpy as np


Creating arrays

In [4]:
v=np.zeros(5)

In [5]:
print(type(v))

<class 'numpy.ndarray'>


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

write a clean code !!! with spaces after every things !!

In [14]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [16]:
arr=np.array([1, 2, 3, 4, 5])
arr[2]=5
print(arr)

[1 2 5 4 5]


In [17]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])


 Create a arrays with evenly spaced numbers within a specified range


In [18]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [19]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### ✅Multi dimensional array

In [20]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.array([[1, 2, 3, 4, 5 ],[4, 5, 6, 7, 8],[2, 3, 4, 5, 5]])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [2, 3, 4, 5, 5]])

In [34]:
arr=np.array([[1, 2, 3, 4, 5 ],[4, 5, 6, 7, 8],[2, 3, 4, 5, 5]])
arr[2, 2]=9
arr

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [2, 3, 9, 5, 5]])

In [38]:
arr[2]=[1, 1, 1, 1, 1]
arr

array([[1, 2, 3, 4, 2],
       [1, 1, 1, 1, 2],
       [1, 1, 1, 1, 1]])

In [39]:
arr[:,4]=[2, 2, 2]
arr

array([[1, 2, 3, 4, 2],
       [1, 1, 1, 1, 2],
       [1, 1, 1, 1, 2]])

In [40]:
arr[1]=np.ones(5)
arr

array([[1, 2, 3, 4, 2],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 2]])

### ✅Randomly generated arrays

- Numpy can create arrays filled with random numbers.
- To ensure the reproducibility , you can set a seed using np.random.seed()
- Everytime you run the code with np.random.seed(2), it will generate the exact same random numbers. If you remove or change the seed values, the sequence of random numbers will be changed .

rand ko number lies between 0 to 1

In [52]:
np.random.rand(5)

array([0.51507375, 0.62224152, 0.98099789, 0.56161461, 0.76923031])

In [70]:
np.random.seed(4)
np.random.rand(5)

array([0.96702984, 0.54723225, 0.97268436, 0.71481599, 0.69772882])

In [71]:
np.random.rand(5,2)

array([[0.2160895 , 0.97627445],
       [0.00623026, 0.25298236],
       [0.43479153, 0.77938292],
       [0.19768507, 0.86299324],
       [0.98340068, 0.16384224]])

In [80]:
np.random.seed(4)
np.random.rand(5,2)

array([[0.96702984, 0.54723225],
       [0.97268436, 0.71481599],
       [0.69772882, 0.2160895 ],
       [0.97627445, 0.00623026],
       [0.25298236, 0.43479153]])

randn will fall under normal distribution that is it generates numbers lies between meu=0 and sigma=1

In [83]:
np.random.randn(5,2)

array([[ 1.69235772, -1.11281215],
       [ 1.63574754, -1.36096559],
       [-0.65122583,  0.54245131],
       [ 0.04800625, -2.35807363],
       [-1.10558404,  0.83783635]])

In [84]:
np.random.seed(43)
np.random.randint(low=0, high=100, size=(5, 2))

array([[68, 64],
       [49, 21],
       [58, 16],
       [51, 17],
       [59, 91]])

### Elements wise operations


In [85]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [86]:
b = (10 + (a * 2))
b

array([10, 12, 14, 16, 18])

In [87]:
# comparison operations
# you can perform element wise comparisons and create boolean arrays

a

array([0, 1, 2, 3, 4])

In [88]:
a>=2

array([False, False,  True,  True,  True])

In [89]:
a > b

array([False, False, False, False, False])

In [90]:
# Summarizing
# Numpy provides function fopr summarizing array of data

a

array([0, 1, 2, 3, 4])

In [91]:
#standard deviation
a.std()

1.4142135623730951

In [92]:
#min value of an array
a.min()

0

In [93]:
# max value of an array

a.max()

4

In [94]:
# sum of the elements of an array

a.sum()

10